# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.0.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ToolBox(object):
    def setupUi(self, ToolBox):
        ToolBox.setObjectName("ToolBox")
        ToolBox.setEnabled(True)
        ToolBox.resize(394, 279)
        self.centralwidget = QtWidgets.QWidget(ToolBox)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 360, 195))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_check_device = QtWidgets.QPushButton(self.layoutWidget)
        self.button_check_device.setObjectName("button_check_device")
        self.verticalLayout.addWidget(self.button_check_device)
        self.button_adb_install = QtWidgets.QPushButton(self.layoutWidget)
        self.button_adb_install.setObjectName("button_adb_install")
        self.verticalLayout.addWidget(self.button_adb_install)
        self.button_catlog = QtWidgets.QPushButton(self.layoutWidget)
        self.button_catlog.setObjectName("button_catlog")
        self.verticalLayout.addWidget(self.button_catlog)
        self.button_aab_install = QtWidgets.QPushButton(self.layoutWidget)
        self.button_aab_install.setObjectName("button_aab_install")
        self.verticalLayout.addWidget(self.button_aab_install)
        self.button_aab_convert = QtWidgets.QPushButton(self.layoutWidget)
        self.button_aab_convert.setObjectName("button_aab_convert")
        self.verticalLayout.addWidget(self.button_aab_convert)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.browser_log = QtWidgets.QTextBrowser(self.layoutWidget)
        self.browser_log.setEnabled(False)
        self.browser_log.setObjectName("browser_log")
        self.horizontalLayout.addWidget(self.browser_log)
        self.label_busy_indicator = QtWidgets.QLabel(self.centralwidget)
        self.label_busy_indicator.setEnabled(True)
        self.label_busy_indicator.setGeometry(QtCore.QRect(20, 200, 51, 41))
        self.label_busy_indicator.setText("")
        self.label_busy_indicator.setObjectName("label_busy_indicator")
        ToolBox.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ToolBox)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 394, 26))
        self.menubar.setObjectName("menubar")
        self.menuAndroid = QtWidgets.QMenu(self.menubar)
        self.menuAndroid.setObjectName("menuAndroid")
        ToolBox.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ToolBox)
        self.statusbar.setObjectName("statusbar")
        ToolBox.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAndroid.menuAction())

        self.retranslateUi(ToolBox)
        QtCore.QMetaObject.connectSlotsByName(ToolBox)

    def retranslateUi(self, ToolBox):
        _translate = QtCore.QCoreApplication.translate
        ToolBox.setWindowTitle(_translate("ToolBox", "ToolBox"))
        self.button_check_device.setText(_translate("ToolBox", "Check Device"))
        self.button_adb_install.setText(_translate("ToolBox", "adb install"))
        self.button_catlog.setText(_translate("ToolBox", "Unity logcat"))
        self.button_aab_install.setText(_translate("ToolBox", "aab install"))
        self.button_aab_convert.setText(_translate("ToolBox", "aab convert"))
        self.browser_log.setHtml(_translate("ToolBox", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuAndroid.setTitle(_translate("ToolBox", "Android"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToolBox = QtWidgets.QMainWindow()
    ui = Ui_ToolBox()
    ui.setupUi(ToolBox)
    ToolBox.show()
    sys.exit(app.exec())
